In [4]:
#soru 1:
import numpy as np
#array oluşturma
array = np.array([10,15,20,25,30,35], dtype= int)

print(f"Array: {array}")
print(f"Array'in boyutu: {  array.ndim}")
print(f"Array'in satır ve sütun sayısı: {array.shape}")
print(f"Array'deki eleman sayısı: {  array.size}")


Array: [10 15 20 25 30 35]
Array'in boyutu: 1
Array'in satır ve sütun sayısı: (6,)
Array'deki eleman sayısı: 6


In [5]:
#soru 2:
# iki boyutlu integer array oluşturma ve bilgilere erişme
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = int)
print(f"Array: {array_2d}")
print(f"Array'in boyutu: {  array_2d.ndim}")
print(f"Array'in eleman sayısı: {array_2d.size}")
print(f"Array'in satır ve sütun sayısı: {array_2d.shape}")

Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array'in boyutu: 2
Array'in eleman sayısı: 9
Array'in satır ve sütun sayısı: (3, 3)


In [6]:
# 2D Array'den belirli bir elemanı seçmek
eleman = array_2d[1, 1]  # 1. satır ve 2. sütundaki eleman (6)
print(f"Seçilen eleman: {eleman}")

dilim = array_2d[:2, 2]  # İlk iki satır, 1. sütun
print(f"Dilimlenmiş array: \n{dilim}")

Seçilen eleman: 5
Dilimlenmiş array: 
[3 6]


In [7]:
# Üç boyutlu integer array oluşturma
array_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                     [[7, 8, 9], [10, 11, 12]]], dtype=int)

print(f"3D Array: \n{array_3d}")
print(f"Array'in boyutu: {array_3d.ndim}")
print(f"Array'in eleman sayısı: {array_3d.size}")
print(f"Array'in boyut bilgisi (derinlik, satır, sütun): {array_3d.shape}")


3D Array: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Array'in boyutu: 3
Array'in eleman sayısı: 12
Array'in boyut bilgisi (derinlik, satır, sütun): (2, 2, 3)


In [8]:
# 3D Array'den belirli bir eleman seçmek
eleman_3d = array_3d[1, 1, 0]
print(f"3D Array'den seçilen eleman: {eleman_3d}")

# 3D Array'in ilk derinliğindeki tüm satırları ve sütunları seçme
dilim_3d = array_3d[1, :, :]  # İlk derinlik, tüm satırlar ve sütunlar
print(f"3D Array'in ilk derinliği: \n{dilim_3d}")



3D Array'den seçilen eleman: 10
3D Array'in ilk derinliği: 
[[ 7  8  9]
 [10 11 12]]


In [9]:
#soru 3:
#a)  Bir boyutlu array oluşturma
import numpy as np
array_1d = np.arange(10)  # 0'dan 9'a kadar olan sayılar
print(f"1D Array: {array_1d}")
# Indexleme
eleman_1d = array_1d[5]
print(f"5. indeksdeki eleman: {eleman_1d}")
# Slicing
dilim_1d = array_1d[3:7]
print(f"3-6 arası dilim: {dilim_1d}")


1D Array: [0 1 2 3 4 5 6 7 8 9]
5. indeksdeki eleman: 5
3-6 arası dilim: [3 4 5 6]


In [10]:
#b) iki boyutlu array oluşturma ve indexleme slicing yapma

array_2d = np.random.randint(1, 10, size=(2, 6))
print(f"2D Array: \n{array_2d}")

# Indexleme
eleman_2d = array_2d[1, 5]
print(f"1. satır, 3. sütundaki eleman: {eleman_2d}")
# Dilimleme
dilim_2d = array_2d[1, :]
print(f"İlk satırın tamamı: {dilim_2d}")
# Dilimleme
dilim_2d_2 = array_2d[:, 1:4]
print(f"Tüm satırlardan 1., 2. ve 3. sütunlar: \n{dilim_2d_2}")


2D Array: 
[[2 6 3 7 1 6]
 [9 3 1 2 8 6]]
1. satır, 3. sütundaki eleman: 6
İlk satırın tamamı: [9 3 1 2 8 6]
Tüm satırlardan 1., 2. ve 3. sütunlar: 
[[6 3 7]
 [3 1 2]]


In [15]:
#c) üç boyutlu array için aynı işlemler

array_3d = np.random.randint(1, 10, size=(2, 4, 4))
print(f"3D Array: \n{array_3d}")

# Indexleme
eleman_3d = array_3d[1, 3, 3]
print(f"1. derinlik, 3. satır, 3. sütundaki eleman: {eleman_3d}")

# Dilimleme
dilim_3d = array_3d[1, :, :]
print(f"1. derinlikteki tüm satır ve sütunlar: \n{dilim_3d}")

# Dilimleme
dilim_3d_2 = array_3d[0, 1:3, 1:3]
print(f"İlk derinlikteki 1. ve 2. satırlardaki 1. ve 2. sütunlar: \n{dilim_3d_2}")


3D Array: 
[[[1 4 6 4]
  [6 4 2 1]
  [6 7 5 7]
  [3 8 5 1]]

 [[6 2 6 7]
  [4 2 9 3]
  [5 9 8 9]
  [1 3 9 2]]]
1. derinlik, 3. satır, 3. sütundaki eleman: 2
1. derinlikteki tüm satır ve sütunlar: 
[[6 2 6 7]
 [4 2 9 3]
 [5 9 8 9]
 [1 3 9 2]]
İlk derinlikteki 1. ve 2. satırlardaki 1. ve 2. sütunlar: 
[[4 2]
 [7 5]]


In [16]:
#soru 4:
import numpy as np

# 3x3 boyutunda sıfırlardan oluşan iki boyutlu array
zeros_array = np.zeros((3, 3), dtype=int)
print(f"Sıfırlardan oluşan array: \n{zeros_array}")

# 3x3 boyutunda birlerden oluşan iki boyutlu array
ones_array = np.ones((3, 3), dtype=int)
print(f"Birlerden oluşan array: \n{ones_array}")


Sıfırlardan oluşan array: 
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Birlerden oluşan array: 
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
# Satır bazında birleştirme
satir_birlesim = np.vstack((zeros_array, ones_array))
print(f"Satır bazında birleştirilmiş array: \n{satir_birlesim}")

# Sütun bazında birleştirme
sutun_birlesim = np.hstack((zeros_array, ones_array))
print(f"Sütun bazında birleştirilmiş array: \n{sutun_birlesim}")


Satır bazında birleştirilmiş array: 
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Sütun bazında birleştirilmiş array: 
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
